config/routes.rb
Rails.application.routes.draw do

  resources :credentials, only: [:index, :show] do
    collection do
      get :cer_intro
      get :cet_style
      get :search
    end
  end
  get 'solution/ict'

  get 'solution/mcc' 

  get 'solution/train_platform'#实训平台

  get 'solution/webthing'

  get 'solution/futclass'

  get 'solution/ViMediaNet'

  get 'solution/swsn'

  get 'solution/find'

  get 'solution/research_base'#研究基地

  get 'solution/key_manager'#钥匙管理

  get 'solution/things'

  get 'solution/en_survey' #工程勘察

  get 'solution/network'#网络优化

  get 'solution/sys_equi'#系统设备
get 'solution/dtce'

  get 'home/error'
  
  resource :abouts ,only: [:show] do
    collection do 
      get :company
      get :dtby
      get :team
      get :job
      get :organization
      get :partner
    end
  end

  get '/college', to: "colleges#index", as: :colleges

  get 'cases/train'
  get 'cases', to: "cases#edu", as: :cases_edu
  get 'cases/industry'
  get 'cases/things'

  get '/enterprise', to: "enterprise#index", as: :enterprise
  get '/techno_college', to: "enterprise#techno_college", as: :techno_college
  get '/project_college', to: "enterprise#project_college", as: :project_college

  get '/education', to: "education#index", as: :educations
  get 'dtce/index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'home/index'

  resources :reports, only: [:index, :show]
  resources :trains

  root 'home#index'

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
# == Schema Information
#
# Table name: banners
#
#  id         :integer          not null, primary key
#  link       :text
#  number     :integer          default(1)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Banner < ActiveRecord::Base
	has_one :image, class_name: "Image", as: :imageable, dependent: :destroy
	accepts_nested_attributes_for :image, :allow_destroy => true
end

app/models/credential.rb
# == Schema Information
#
# Table name: credentials
#
#  id              :integer          not null, primary key
#  name            :string
#  cer_number      :string
#  score           :integer
#  cer_type        :string
#  start_date      :date
#  end_date        :date
#  identity_number :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Credential < ApplicationRecord
	validates_uniqueness_of :cer_number, :message => "该证书已存在!"
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                 :integer          not null, primary key
#  desc               :string
#  imageable_id       :integer
#  imageable_type     :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#

class Image < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true

  # paperclip gem
  has_attached_file :photo, :styles => { :mini => '48x48>', :small => '100x100>', :medium => '200x200>', :product => '320x320>', :large => '600x600>', :news => '130x85>', :banner => '1400x502' }

  validates_attachment_presence :photo
  validates_attachment_size     :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
end

app/models/recruit.rb
# == Schema Information
#
# Table name: recruits
#
#  id         :integer          not null, primary key
#  position   :string
#  address    :string
#  quantity   :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Recruit < ActiveRecord::Base
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :integer          default("company")
#  source     :string
#  view_count :integer
#

class Report < ActiveRecord::Base
  has_one :image, class_name: "Image", as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :image, :allow_destroy => true

  enum category: {company: 1, industry: 2, activity: 3}
  ReportCategory = {company: '公司新闻', industry: '行业动态', activity: '最新活动'}
end

app/models/train.rb
# == Schema Information
#
# Table name: trains
#
#  id         :integer          not null, primary key
#  about      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Train < ActiveRecord::Base
	# has_mary :image, class_name: "Image", as: :imageable, dependent: :destroy
  # accepts_nested_attributes_for :image, :allow_destroy => true
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def edu
    @pic_text={
      "1"=>"多功能ICT展厅",
      "2"=>"移动通信实训室",
      "3"=>"WEB软件开发实训室",
      "4"=>"IOS软件开发实训室",
      "5"=>"物联网实训室",
      "6"=>"智慧农业实训系统",
      "7"=>"设备管理实训系统"
    }
  end

  def train
    @train_text={
      "1"=>"移动互联网产教研协同基地培训班开班典礼",
      "2"=>"领导致辞",
      "3"=>"实习实训结业典礼",
      "4"=>"安师大学生实训课程"
    }
  end

  def industry
    @pic_text={
     "8"=>"上海浦东气象局微信公众号开发",
     "9"=>"上海市气象局业务平台开发项目",
     "10"=>"上海弘飞等洗涤设备企业的自动化控制系统",
     "11"=>"上海大众整车厂VDC仓储系统"
    }
  end

  def things
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @banners = Banner.all.order(:number)
    company_news = Report.where(category:1).order("created_at DESC")
    if company_news.count < 5
      @firms = company_news.limit(company_news.count)
      @trades = Report.where(category:2).order("created_at DESC").limit(5 - company_news.count)
    else
      @firms = company_news.limit(5)
      @trades = []
    end
  end

  def error
    render :layout => false
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
	def things_image_text index
		cache = {
			0 => "移动互联网/物联网嵌入式教学科研平台",
			1 => "移动互联网/物联网嵌入式教学科研平台",
			2 => "智能交通管理实训系统",
			3 => "智能交通管理实训系统",
			4 => "智能交通管理实训系统",
			5 => "智能家居实训系统",
			6 => "智能家居实训系统",
			7 => "智能家居实训系统",
			8 => "港口物流交通实训系统",
			9 => "港口物流交通实训系统"
		}
		return cache[index]
	end
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/enterprise_helper.rb
module EnterpriseHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def active_head_content report
    "<h4 class=\"list-group-item-heading blue\">#{report.title} <small>[#{report.created_at.to_date}]</small></h4>"
  end

  def head_content report
    "<h5 class=\"list-group-item-heading\">#{report.title} <small>[#{report.created_at.to_date}]</small></h5>"
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/solution_helper.rb
module SolutionHelper
end

app/helpers/train_helper.rb
module TrainHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/dtce/dtce.html.erb
<div class="container-fluid">
  <%= image_tag "dtce-top.jpg", width: "100%" %>
</div>
<div class="container">
	<div class="row">
    <div class="col-md-2 col-md-offset-5 p-title">
      <span class="clearfix">ABOUT DTCE</span>
      <span class="title">关于DTCE</span>
    </div>
  </div>
  <div class="row">
  	<div class="col-md-7 dtce-about">
  		<p>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DTCE（Datang Technology Certified Engineer）是大唐邦彦与大唐大学联合组织的职业资格认证体系，针对ICT行业急需的专业人才方向，订制了移动通信技术、移动互联网应用技术以及物联网应用技术3大类12个专业的认证。<br/>
				大唐邦彦与高校的友好合作，将以联合人才培养和基地建设为起点，首先以专业共建的模式，共同开拓和建设移动通信和物联网络相关专业学科，并共同建设配套的专业实训基地，共同培养3G\4G移动通信网络优化人才和物联网应用开发人才；其次企业将帮助高校进行“双师型”骨干教师的培养，并在此基础上利用企业和高校的优势资源，开展行业内前沿科研创新课题的共同研究，将校企合作实训基地打造成为区域移动通信和物联网络人才培养基地，对外输出科研成果和人才培养服务，实现自我造血功能，逐步提升彼此在区域内的影响力。
  		</p>
  	</div>
  	<div class="col-md-5 text-center">
  		<%= image_tag "dtce-1.jpg" %>
			<small class="clearfix">校企合作服务</small>
  	</div>
  </div>
</div>
<div class="container-fluid gray-panel">
	<div class="container">
		<div class="row">
	    <div class="col-md-2 col-md-offset-5 p-title">
	      <span class="clearfix">CERTIFICATE SAMPLE</span>
	      <span class="title">证书样本</span>
	    </div>
	  </div>
	  <div class="row mt text-center">
	  	<%= image_tag "certificate_sample.jpg" %>
	  </div>
	</div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 p-title">
      <span class="clearfix">VOCATIONAL QUALIFICATION</span>
      <span class="title">职业资格认证体系</span>
    </div>
  </div>
  <div class="row">
    <table class="table table-striped">
      <tr>
        <th>认证方向</th>
        <th>专业方向</th>
        <th>配套教学设备</th>
        <th>高级</th>
        <th>中级</th>
        <th>初级</th>
      </tr>
      <tr>
        <td rowspan="6" class="bg_color">移动通信技术</td>
        <td>3G/4G网络规划优化</td>
        <td>规划软件、路测设备、测试手机、34G主设备</td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
      </tr>
      <tr>
        <td>3G/4G设备维护</td>
        <td>34G主设备、操作维护软件</td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
      </tr>
      <tr>
        <td>室内分布集成</td>
        <td>室分设备</td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
      </tr>
      <tr>
        <td>综合布线</td>
        <td>综合布线实验室</td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
      </tr>
      <tr>
        <td>智能终端检测维修</td>
        <td>手机维修测试工具</td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td></td>
      </tr> 
      <tr>
        <td>APP认证</td>
        <td></td>
        <td></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td></td>
      </tr>
      <tr>
        <td rowspan="4" class="bg_color">移动互联网技术</td>
        <td>Web应用(后端)</td>
        <td>开发平台</td>
        <td></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
      </tr>
      <tr>
        <td>APP应用开发(Android方向)</td>
        <td>开发平台</td>
        <td></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
      </tr>
      <tr>
        <td>APP应用开发(IOS方向)</td>
        <td>开发平台</td>
        <td></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
      </tr>
      <tr>
        <td>Web应用(前端)</td>
        <td>开发平台</td>
        <td></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td><%= image_tag "icon_ok.png" %></td>
      </tr>
      <tr>
        <td class="bg_color">物联网应用技术</td>
        <td>嵌入式开发</td>
        <td>开发板</td>
        <td></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td></td>
      </tr>
      <tr>
        <td class="bg_color">智能终端开发设计</td>
        <td>开发板</td>
        <td></td>
        <td></td>
        <td><%= image_tag "icon_ok.png" %></td>
        <td></td>
      </tr>
    </table>
  </div>
</div>

app/views/share/_baidu_share.html.erb
<div class="bdsharebuttonbox baidu-share">
	<span>分享：</span>
	<a href="#" class="bds_more" data-cmd="more"></a>
	<a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
	<a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
	<a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a>
	<a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a>
	<a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
</div>
<script>
	window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"16"},"share":{}};
	with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];
</script>

app/views/share/_footer.html.erb
<div class="footer bgc-gray">
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-sm-2">
				<ul class="nav nav-justified">
					<li>
						关于我们<br>
						<small><%= link_to "公司架构", company_abouts_path%></small><br>
						<small><%= link_to "领导介绍", dtby_abouts_path%></small><br>
						<small><%= link_to "荣誉奖励", "#"%></small><br>
						<small><%= link_to "大事记", "#"%></small>
					</li>
				</ul>
			</div>
			<div class="col-xs-6 col-sm-2">
				<ul class="nav nav-justified">
					<li>
						新闻中心<br>
						<small><%= link_to "新闻资讯", reports_path%></small><br>
						<small><%= link_to "行业动态", reports_path(category: "industry")%></small><br>
						<small><%= link_to "合作支持", enterprise_path %></small><br>
					</li>
				</ul>
			</div>
			<div class="col-xs-6 col-sm-2">
				<ul class="nav nav-justified">
					<li>
						联系我们<br>
						<small><%= link_to "地图", "#"%></small><br>
						<small><%= link_to "招聘", job_abouts_path %></small><br>
						<small><%= link_to "意见反馈", "#"%></small><br>
						<small><%= link_to "联系电话", "#"%></small>				
					</li>
				</ul>
			</div>
			<div class="col-xs-6 col-sm-2">
				<ul class="nav nav-justified">
					<li>
						友情链接<br>
						<small><%= link_to "大唐电信", "http://www.datanggroup.cn/",target:"_blank"%></small><br>
						<small><%= link_to "大唐移动", "http://mobile.datanggroup.cn/a_about.aspx",target:"_blank"%></small><br>
						<small><%= link_to "慕课网", "http://www.imooc.com/",target:"_blank"%></small>
					</li>
				</ul>
			</div>
			<div class="col-xs-6 col-sm-2 text-center">
				<%= image_tag("wechat.png")%>
			</div>
			<div class="col-xs-6 col-sm-2 text-center">
				<%= image_tag("micropost.png")%>
			</div>
		</div>
	</div>
</div>

<div class="text-center bgc-gray-dark">
	<small>© Copyright 2015 buoyantec.com 邦彦网</small>
</div>

app/views/share/_head.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menuContent">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
      	<%= image_tag "logo.png" %>
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="menuContent">
      <ul class="nav navbar-nav">
        <li class=<%= "active" if params[:controller] == "home" %>>
          <%= link_to("首页", root_path) %>
        </li>
        <li class=<%= "active" if params[:controller] == "reports" %>>
          <%= link_to("新闻中心", reports_path) %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to("公司新闻", "#{reports_path(category: "company")}#news") %></li>
            <li><%= link_to("行业动态", "#{reports_path(category: "industry")}#news") %></li>
            <li><%= link_to("最新活动", "#{reports_path(category: "activity")}#news") %></li>
          </ul>
        </li>
        <li class=<%= "active" if params[:controller] == "education" %>><%= link_to("在线教育", educations_path) %></li>
        <li class=<%= "active" if params[:controller] == "solution" %>>
          <%= link_to("产品与解决方案", solution_ict_path) %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to("ICT综合智慧展厅", "#{solution_ict_path}#solutionContent") %></li>
            <li><%= link_to("移动通信实训中心", "#{solution_mcc_path}#solutionContent") %></li>
            <li><%= link_to("移动通信虚拟现实实训平台", "#{solution_train_platform_path}#solutionContent") %></li>
            <li><%= link_to("物联网实训中心", "#{solution_webthing_path}#solutionContent") %></li>
            <li><%= link_to("未来教室融合", "#{solution_futclass_path}#solutionContent") %></li>
            <li><%= link_to("ICT综合产品研究基地", "#{solution_research_base_path}#solutionContent") %></li>
            <li><%= link_to("移动通信工程勘察", "#{solution_en_survey_path}#solutionContent") %></li>
            <li><%= link_to("移动通信网络优化", "#{solution_network_path}#solutionContent") %></li>
            <li><%= link_to("移动通信系统设备", "#{solution_sys_equi_path}#solutionContent") %></li>
            <li><%= link_to("钥匙管理系统", solution_key_manager_path) %></li>
            <li><%= link_to("物联网产品", solution_things_path) %></li>
            <li><%= link_to("安防仿真平台", solution_ViMediaNet_path) %></li>
            <li><%= link_to("环境感知系统", solution_swsn_path) %></li>
            <li><%= link_to("设备查找系统", solution_find_path) %></li>
          </ul>
        </li>
        <li class=<%= "active" if params[:controller] == "credentials" %>>
          <%= link_to("DTCE证书", cer_intro_credentials_path) %>
           <ul class="dropdown-menu" role="menu">
            <li><%= link_to  "证书样本",  cet_style_credentials_path %></li>
            <li><%= link_to  "证书查询",  search_credentials_path %></li>
          </ul>
        </li>
        <li class=<%= "active" if params[:controller] == "enterprise" %>>
          <%= link_to("校企合作", enterprise_path) %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to  "大唐信息技术学院",  techno_college_path %></li>
            <li><%= link_to  "大唐电子信息工程学院",  project_college_path %></li>
          </ul>
        </li>
        <li class=<%= "active" if params[:controller] == "cases" %>>
          <%= link_to("成功案例", cases_edu_path) %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to  "教育合作案例",  cases_edu_path %></li>
            <li><%= link_to  "培训案例",  cases_train_path %></li>
            <li><%= link_to  "行业信息化案例",  cases_industry_path %></li>
            <li><%= link_to  "物联网案例",  cases_things_path %></li>
          </ul>
        </li>
        <li class=<%= "active" if params[:controller] == "abouts" %>><%= link_to("关于我们", company_abouts_path) %>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to  "公司简介",  company_abouts_path %></li>
            <li><%= link_to  "邦彦文化",  dtby_abouts_path %></li>
            <li><%= link_to  "团队介绍",  team_abouts_path %></li>
            <li><%= link_to  "招聘信息",  job_abouts_path %></li>
            <li><%= link_to  "战略伙伴",  partner_abouts_path %></li>
            <li><%= link_to  "分支机构",  organization_abouts_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<script type="text/javascript">
  $(function(){
    $("#menuContent ul li").mouseenter(function(){
      $(this).addClass("open");
      $(this).find("a").attr("aria-expanded",true)
    });
    $("#menuContent ul li").mouseleave(function(){
      $(this).removeClass("open");
      $(this).find("a").attr("aria-expanded",false)
    });
  });
</script>