config/routes.rb
Rails.application.routes.draw do

  resources :credentials, only: [:index, :show] do
    collection do
      get :cer_intro
      get :cet_style
      get :search
    end
  end
  get 'solution/ict'

  get 'solution/mcc' 

  get 'solution/train_platform'#实训平台

  get 'solution/webthing'

  get 'solution/futclass'

  get 'solution/ViMediaNet'

  get 'solution/swsn'

  get 'solution/find'

  get 'solution/research_base'#研究基地

  get 'solution/key_manager'#钥匙管理

  get 'solution/things'

  get 'solution/en_survey' #工程勘察

  get 'solution/network'#网络优化

  get 'solution/sys_equi'#系统设备
get 'solution/dtce'

  get 'home/error'
  
  resource :abouts ,only: [:show] do
    collection do 
      get :company
      get :dtby
      get :team
      get :job
      get :organization
      get :partner
    end
  end

  get '/college', to: "colleges#index", as: :colleges

  get 'cases/train'
  get 'cases', to: "cases#edu", as: :cases_edu
  get 'cases/industry'
  get 'cases/things'

  get '/enterprise', to: "enterprise#index", as: :enterprise
  get '/techno_college', to: "enterprise#techno_college", as: :techno_college
  get '/project_college', to: "enterprise#project_college", as: :project_college

  get '/education', to: "education#index", as: :educations
  get 'dtce/index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'home/index'

  resources :reports, only: [:index, :show]
  resources :trains

  root 'home#index'

end

app/models/train.rb
# == Schema Information
#
# Table name: trains
#
#  id         :integer          not null, primary key
#  about      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Train < ActiveRecord::Base
	# has_mary :image, class_name: "Image", as: :imageable, dependent: :destroy
  # accepts_nested_attributes_for :image, :allow_destroy => true
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params[:train]
    end
end

app/helpers/train_helper.rb
module TrainHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form' %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<div class="container-fluid">
  <%= image_tag "train-top-bg.jpg", width: "100%", class:"banner-margin"%>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-2 col-md-offset-5 train-title">
      <span class="clearfix">ABOUT CULTIVATE</span>
      <span class="title">关于培训</span>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2 train-about">
      <p>
        &nbsp;&nbsp;&nbsp;&nbsp;大唐邦彦聚焦移动互联网前沿技术的教育和培训业务，将科技创新成果和教育培训产业带相互融合，"推动"，以产业引导教育改革的长期发展战略，结合校企双方优势，倡导以教育信息化培训产业人才的商业，为国家持续输送高技术人才。
      </p>
    </div>
  </div>
  <div class="row train-line">
    <div class="col-md-5">
      <hr />
    </div>
    <div class="col-md-2 text-center">
      <span class="title">教学环境</span>
    </div>  
    <div class="col-md-5">
      <hr />
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag "train-1.jpg", width: "100%" %>
    </div>
    <div class="col-md-3">
      <%= image_tag "train-2.jpg", width: "100%" %>
    </div>
    <div class="col-md-3">
      <%= image_tag "train-3.jpg", width: "100%" %>
    </div>
    <div class="col-md-3">
      <%= image_tag "train-4.jpg", width: "100%" %>
    </div>
  </div>
</div>
<div class="container-fluid train-gray-panel">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-5 train-title">
        <span class="clearfix">OUR ADVANTAGE</span>
        <span class="title">关于培训</span>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 advantage">
        <div class="item">
          <div class="title">
            产业支撑
          </div>
          <div class="content">
            坐拥大唐电信集团拥有无线移动通信、集成电路设计与制造、特种通信和先导产业四大产业板块总资产规模近500亿人民币规模的产业平台
          </div>  
        </div>
      </div>
      <div class="col-md-3 advantage">
        <div class="item">
          <div class="title">
            平台支撑
          </div>
          <div class="content">
            集"中国企业教育先进单位百强"、"中国最佳企业大学"等多项荣誉为一身的大唐大学提供完善的DTCE培训及认证体系支撑
          </div>  
        </div>
      </div>
      <div class="col-md-3 advantage">
        <div class="item">
          <div class="title">
            师资支撑
          </div>
          <div class="content">
            提供"双技能"教师，既有多年电信研究院研发及项目经验，同时具备企业内训师资格，研发和授课实力超强，充分满足"应用型"人才教育的需求
          </div>  
        </div>
      </div>
      <div class="col-md-3 advantage">
        <div class="item">
          <div class="title">
            实战支撑
          </div>
          <div class="content">
            邦彦精准打造"全栈工程师"，从自身多个在建开发项目中选取适合教学的模块进行实操，真正做到"实践出真知"，短期内能力迅速提升
          </div>  
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 advantage">
        <div class="item">
          <div class="title">
            硬件支撑
          </div>
          <div class="content">
            在上海拥有设备先进的培训基地————"大唐职业技术学院"。配备全套IOS实训室、安卓实训室、物联网实训室以及移动通讯实训室，可同时容纳200名学员同时上课
          </div>  
        </div>
      </div>
      <div class="col-md-3 advantage">
        <div class="item">
          <div class="title">
            资金支撑
          </div>
          <div class="content">
            作为中央直属企业，大唐邦彦担负社会责任，本着为减轻学生负担原则，在以高校为担保的前提下，提供"大唐助学金"计划，收取低额的保证金即可参与培训，待就业后分期支付培训费用
          </div>  
        </div>
      </div>
      <div class="col-md-3 advantage">
        <div class="item">
          <div class="title">
            就业支撑
          </div>
          <div class="content">
            大唐电信集团内部企业对有"DTCE资格认证"学员优先考虑就业。且在多家业内知名合作伙伴，包括晨讯集团、龙旗控股、腾讯创业基地等多家上市公司和创业园区进行就业推荐
          </div>  
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-2 col-md-offset-5 train-title">
      <span class="clearfix">COURSE CHARACTERISTIC</span>
      <span class="title">课程特色</span>
    </div>
  </div>
  <div class="row course-div">
    <div class="col-md-6">
      <%= image_tag "train-5.jpg", width: "100%" %>
    </div>
    <div class="col-md-6">
      <div class="course">
        <div class="title">
          课程设计科学合理
        </div>
        <div class="content">
          <p>本培训班的课程划分为3个层次:基础知识 - 核心技术 - 项目实战<br/>通过本培训班的学习，学员能够系统地、循序渐进地学到先进的、符合实际需求的基础知识和实用软件开发技术。</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row course-div">
    <div class="col-md-6">
      <div class="course">
        <div class="title">
          需求决定教学内容
        </div>
        <div class="content">
          <p>本项目课程的设计者是在大唐电信工作并长期从事软件开发的第一线高级工程师；各门课程的教学内容都是根据应用开发的需求而确定的，并遵循"必须、够用"的原则；可以说，该项目教学内容凝聚了大唐电信一线研发人员多年的开发经验和工作体会。</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag "train-6.jpg", width: "100%" %>
    </div>
  </div>
  <div class="row course-div">
    <div class="col-md-6">
      <%= image_tag "train-7.jpg", width: "100%" %>
    </div>
    <div class="col-md-6">
      <div class="course">
        <div class="title">
          丰富的实践环节
        </div>
        <div class="content">
          <p>本培训班安排了大量的上机实践环节，尤其是最后的项目训练，使学员在应用开发能力方面得到显著提高。</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row course-div">
    <div class="col-md-6">
      <div class="course">
        <div class="title">
          职业化启航训练
        </div>
        <div class="content">
          <p>本培训除了理论和实践培训以外，还将大唐电信企业文化引入课堂，帮助在校大学生明确职场定位、提高职业素养、增强求职技能、拓宽职场人脉，奠定职业生涯的发展基础。</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag "train-8.jpg", width: "100%" %>
    </div>
  </div>
</div>
<div class="container-fluid train-gray-panel">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-5 train-title">
        <span class="clearfix">COURSE CONTANT</span>
        <span class="title">课程内容</span>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="thumbnail">
          <%= image_tag "train-9.jpg", width: "100%" %>
          <div class="caption">
            <h4>课程名称：Web实战开发</h4>
            <p>课程描述：<br/>1. Web敏捷开发理念，介绍团队协同开发理念和工作流程，介绍项目管理工具、源代码管理工具（Git）等Web工作整体开发流程。<br/>2. Web前端开发基础，以Twitter Bootstrap为基础进行介绍，讲解 Bootstrap 框架的基础，通过学习这些内容，您将可以轻松地创建 Web 项目。教程被分为 Bootstrap 基本结构、Bootstrap CSS、Bootstrap 布局组件和 Bootstrap 插件几个部分。每个部分都包含了与该主题相关的简单有用的实例。<br/>3. Web服务器开发基础，全面讲述了Ruby On Rails的各类技术应用，从零基础开始讲解Ruby的应用，并采用案例配合教学的方式，课程贯穿各类案例，让学生可以在最短的时间内学会Ruby，课程最终以项目实战进行巩固，可让学生自如应用之前学到的各类技术。<br/>课程特点：常规授课、互动讨论、案例剖析、上机实践、线下答疑、项目实战<br/>对应职位：Ruby开发工程师、Web开发工程师</p>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="thumbnail">
          <%= image_tag "train-10.jpg", width: "100%" %>
          <div class="caption">
            <h4>课程名称：Android应用实战开发</h4>
            <p>课程描述：<br/>1. Android开发基础，包括Android开发基础、Java语言基础、OOP编程、Java核心API、Android UI基础五大模块。<br/>2. Android核心技术，包括数据存储、线程通信、Android组件、电话技术、GPS及位置服务-BaiduMap服务、Android4.x新特性六大模块。<br/>3. Android高级技术，包括Android高级绘图、Android高级控件、商业应用项目结构分析及设计三大模块。<br/>4. Android项目实践。<br/>课程特点：常规授课、互动讨论、案例剖析、上机实践、线下答疑、项目实战<br/>对应职位：Android开发工程师、终端应用开发工程师</p>
          </div>
        </div>  
      </div>
    </div>
  </div>
</div>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form' %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>