config/routes.rb
Rails.application.routes.draw do

  resources :credentials, only: [:index, :show] do
    collection do
      get :cer_intro
      get :cet_style
      get :search
    end
  end
  get 'solution/ict'

  get 'solution/mcc' 

  get 'solution/train_platform'#实训平台

  get 'solution/webthing'

  get 'solution/futclass'

  get 'solution/ViMediaNet'

  get 'solution/swsn'

  get 'solution/find'

  get 'solution/research_base'#研究基地

  get 'solution/key_manager'#钥匙管理

  get 'solution/things'

  get 'solution/en_survey' #工程勘察

  get 'solution/network'#网络优化

  get 'solution/sys_equi'#系统设备
get 'solution/dtce'

  get 'home/error'
  
  resource :abouts ,only: [:show] do
    collection do 
      get :company
      get :dtby
      get :team
      get :job
      get :organization
      get :partner
    end
  end

  get '/college', to: "colleges#index", as: :colleges

  get 'cases/train'
  get 'cases', to: "cases#edu", as: :cases_edu
  get 'cases/industry'
  get 'cases/things'

  get '/enterprise', to: "enterprise#index", as: :enterprise
  get '/techno_college', to: "enterprise#techno_college", as: :techno_college
  get '/project_college', to: "enterprise#project_college", as: :project_college

  get '/education', to: "education#index", as: :educations
  get 'dtce/index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'home/index'

  resources :reports, only: [:index, :show]
  resources :trains

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @banners = Banner.all.order(:number)
    company_news = Report.where(category:1).order("created_at DESC")
    if company_news.count < 5
      @firms = company_news.limit(company_news.count)
      @trades = Report.where(category:2).order("created_at DESC").limit(5 - company_news.count)
    else
      @firms = company_news.limit(5)
      @trades = []
    end
  end

  def error
    render :layout => false
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def active_head_content report
    "<h4 class=\"list-group-item-heading blue\">#{report.title} <small>[#{report.created_at.to_date}]</small></h4>"
  end

  def head_content report
    "<h5 class=\"list-group-item-heading\">#{report.title} <small>[#{report.created_at.to_date}]</small></h5>"
  end
end

app/views/home/_ad.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators buoyan-tec-carousel">
    <% banners.each_with_index do |banner, index| %>
      <li data-target="#carousel-example-generic" data-slide-to="<%= index %>" class="<%= "active" if index == 0 %>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% banners.each_with_index do |banner, index| %>
      <div class="item <%= "active" if index == 0 %>">
        <a href="<%= banner.link %>">
          <%= image_tag "#{banner.image.photo(:banner)}", style: "width: 100%", class: "banner-margin carousel-image", alt: "大唐邦彦(上海)信息技术有限公司"%>
        </a>
      </div>
    <% end %>
  </div>
</div>

app/views/home/_intro.html.erb
<div class="container">
	<div class="row intro m-row">
		<div class="home-title text-center">
			<h4>核心业务</h4>
			<%= image_tag "home_page_2.png", class:"home-title-icon"%>
		</div>
		<div class="col-md-3 col-xs-6 m-col">
			<%= link_to cases_train_path do %>
				<%= image_tag "index_info1.png" %>
				<div class="intro-content text-justify">
					<h4 class="text-center">培 训</h4>
					<br>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;大唐邦彦聚焦移动互联网前沿技术的教育和培训业务，将科技创新成果与教育培训产业带相结合，推动“以产业引导教育改革”的长期发展战略。结合双方优势，为国家持续输送高科技人才。...
				</div>
			<% end %>
		</div>
		<div class="col-md-3 col-xs-6 m-col">
			<!-- <%= link_to solution_dtce_path do %>
				<%= image_tag "index_info2.png" %>
				<div class="intro-content text-justify">
					<h4 class="text-center">DTCE认证</h4>
					<br>
					&nbsp;&nbsp;&nbsp;&nbsp;DTCE（Datang Technology Certifiled Engineer）是大唐邦彦与大唐大学联合组织的职业资格认证体系，针对ICT行业急需的专业人才方向，订制了移动通信技术、移动互联网应用技术以及物联网应用技术3大类12个专业的认证。...
				</div>
			<% end %> -->
		</div>
		<div class="col-md-3 col-xs-6 m-col">
			<%= link_to enterprise_path do %>
				<%= image_tag "index_info3.png" %>
				<div class="intro-content text-justify">
					<h4 class="text-center">校企合作</h4>
					<br>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;大唐电信与包括北京大学、清华大学、北京邮电大学、西安电子科技大学、中科院计算所等17所高效进行战略合作，于2008年7月2日在京签署了战略合作协议。经过几年的合作探索，已经与全国数十所高校建立合作关系。...
				</div>
			<% end %>
		</div>
		<div class="col-md-3 col-xs-6 m-col">
			<%= link_to educations_path do %>
				<%= image_tag "index_info4.png" %>
				<div class="intro-content text-justify">
					<h4 class="text-center">在线教育</h4>
					<br>
					&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;在线教育平台即在线培训系统是实施在线培训，在线教育的工具软件，一个运用网络技术与软件技术，可以定制和扩展的远程网上教育学院，它通过简单易用的课件、试题导入和制作功能...
				</div>
			<% end %>
		</div>
	</div> 
	<br>
</div>

app/views/home/_reports.html.erb
<div class="container reports">
	<div class="home-title text-center">
		<h4>新闻资讯</h4>
		<%= image_tag "home_page_2.png", class:"home-title-icon"%>
	</div>
	<table class="table table-hover">			
		<tbody>
			<% @firms.each do |report|%>
				<tr>
					<td class="report-time">
						<div class="report-day"><%= report.created_at.strftime "%d"%></div>
						<span><%= report.created_at.strftime "%Y-%m"%></span>
					</td>
					<td class="report-img text-left">
						<%= image_tag( report.image .present? ? report.image.photo(:news) : "index-reports1.jpg")%>
					</td>
					<td class="text-left">
						<h4><%= link_to "#{report.title}", report_path(report) %></h4>
						<div class="report-info"><%= sanitize(report.content, tags: %w(span), attributes: %w(href)) %></div>
					</td>
				</tr>
			<% end %>
			<% @trades.each do |report|%>
				<tr>
					<td class="report-time">
						<div class="report-day"><%= report.created_at.strftime "%d"%></div>
						<span><%= report.created_at.strftime "%Y-%m"%></span>
					</td>
					<td class="report-img text-left">
						<%= image_tag( report.image .present? ? report.image.photo(:news) : "index-reports1.jpg")%>
					</td>
					<td class="text-left">
						<h4><%= link_to "#{report.title}", report_path(report) %></h4>
						<div class="report-info"><%= sanitize(report.content,tags: %w(span), attributes: %w(href)) %></div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<div class="text-center">
		<%= link_to reports_path do %>
			<h5 class="report-more">
				查看更多 <span><%= image_tag "home_page_3.png"%></span>
			</h5>
		<% end %>
	</div>
	<!-- <div class="home-ad">
		<%#= image_tag "home_ad.png", width:"100%"%>
	</div> -->
</div>

app/views/home/error.html.erb
<%= image_tag "error.jpg" %>

app/views/home/index.html.erb
<%= render partial: "ad", locals: { banners: @banners } %>

<%= render partial: "reports" %>

<%= render partial: "intro" %>