config/routes.rb
Rails.application.routes.draw do

  resources :credentials, only: [:index, :show] do
    collection do
      get :cer_intro
      get :cet_style
      get :search
    end
  end
  get 'solution/ict'

  get 'solution/mcc' 

  get 'solution/train_platform'#实训平台

  get 'solution/webthing'

  get 'solution/futclass'

  get 'solution/ViMediaNet'

  get 'solution/swsn'

  get 'solution/find'

  get 'solution/research_base'#研究基地

  get 'solution/key_manager'#钥匙管理

  get 'solution/things'

  get 'solution/en_survey' #工程勘察

  get 'solution/network'#网络优化

  get 'solution/sys_equi'#系统设备
get 'solution/dtce'

  get 'home/error'
  
  resource :abouts ,only: [:show] do
    collection do 
      get :company
      get :dtby
      get :team
      get :job
      get :organization
      get :partner
    end
  end

  get '/college', to: "colleges#index", as: :colleges

  get 'cases/train'
  get 'cases', to: "cases#edu", as: :cases_edu
  get 'cases/industry'
  get 'cases/things'

  get '/enterprise', to: "enterprise#index", as: :enterprise
  get '/techno_college', to: "enterprise#techno_college", as: :techno_college
  get '/project_college', to: "enterprise#project_college", as: :project_college

  get '/education', to: "education#index", as: :educations
  get 'dtce/index'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'home/index'

  resources :reports, only: [:index, :show]
  resources :trains

  root 'home#index'

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  category   :integer          default("company")
#  source     :string
#  view_count :integer
#

class Report < ActiveRecord::Base
  has_one :image, class_name: "Image", as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :image, :allow_destroy => true

  enum category: {company: 1, industry: 2, activity: 3}
  ReportCategory = {company: '公司新闻', industry: '行业动态', activity: '最新活动'}
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  # GET /reports
  def index
    if  params[:category].blank?
      @reports = Report.all.order("created_at DESC").per_page_kaminari(params[:page]).per(15)
    else
      @reports = Report.where(category: Report.categories[params[:category]]).order("created_at DESC").per_page_kaminari(params[:page]).per(15)
    end
  end

  # GET /reports/1
  def show
    @report = Report.find(params[:id])
    @report.update(view_count: @report.view_count.present? ? (@report.view_count + 1) : 1)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_left_nav.html.erb
<div id="leftMenu" class="content text-center">
	<div class="left-head">新闻中心</div>
	<div class="left-body">
		<ul class="nav">
			<li role="presentation" class="<%= "active" if params[:category] == "company"%>"><%= link_to "公司新闻", "#{reports_path(category: "company")}#news" %></li>
			<hr class="divider">
			<li role="presentation" class="<%= "active" if params[:category] == "industry"%>"><%= link_to "行业动态", "#{reports_path(category: "industry")}#news" %></li>
			<hr class="divider">
			<li role="presentation" class="<%= "active" if params[:category] == "activity"%>"><%= link_to "最新活动", "#{reports_path(category: "activity")}#news" %></li>
		</ul>
	</div>
</div>

app/views/reports/_right_head_nav.html.erb
<ul class="nav nav-pills">
	<li>
		<span><%= image_tag "news_nav_icon.png"%>&nbsp;&nbsp;当前位置:&nbsp;&nbsp;</span>
	</li>
	<li>
		<ol class="breadcrumb top_h">
			<li><%= link_to "首页", home_index_path %></li>
			<li><%= link_to "新闻中心", reports_path %></li>
			<% if params[:category].present? %>
				<li><%= link_to Report::ReportCategory[params[:category].to_sym], reports_path(category: params[:category]) %></li>
			<% end %>
			<% if params[:id].present? %>
				<li class="active">正文</li>
			<% else %>
				<li class="active">全部新闻</li>
			<% end %>
		</ol>
	</li>
</ul>	

app/views/reports/index.html.erb
<%= image_tag "news_banner.jpg", width:"100%", class:"banner-margin"%>
<div class="container">
	<div class="row" id="news">
		<div class="col-md-3">
			<%= render "left_nav" %>
		</div>
		<div class="col-md-9">
			<div class="content">
				<div class="right-head">
					<%= render "right_head_nav" %>				
				</div>
				<div class="right-body">
					<ul class="nav nav-stacked reports-index">    
						<% @reports.each do |report| %>   
							<li role="presentation">
								<%= link_to "#{report_path(report, category: params[:category])}#news" do %>
									<div class="row reports-index">
										<div class="col-xs-10">
											<span><%= image_tag "news_li_dot.png"%>
											</span>&nbsp;&nbsp;<%= report.title %>
										</div>
										<div class="col-xs-2 text-right">[<%= report.created_at.strftime "%F"%>]</div>
									</div>
								<% end %>
							</li>
						<% end %>
					</ul>
					<br>
					<div class="paginate text-center"><%= paginate @reports, category: params[:category] %></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/reports/show.html.erb
<div class="container-fluid">
	<%= image_tag "news_banner.jpg", class:"img-responsive"%>
</div>
<br>
<div class="bgc-gray">
	<div class="container">
		<div class="row" id="news">
			<div class="col-md-3">
				<%= render "left_nav" %>
			</div>
			<div class="col-md-9">
				<div class="content">
					<div class="right-head">
						<%= render "right_head_nav" %>	
					</div>
					<div class="right-body">
						<div class="container-fluid text-center">
							<h2><%= @report.title %></h2>
						</div>
						<hr class="divider">
						<div class="text-justify news-content">
							<ul class="nav-justified">
								<li>发布时间: <%= @report.created_at.strftime "%F"%></li>
								<li>浏览次数: <%= @report.view_count %>次</li>
								<li>来源: <%= @report.source %></li>
								<li>
									<%= render "share/baidu_share" %>
								</li>
							</ul>
							<div class="news-article"><%= raw @report.content%></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>